# Generated by Django 4.1 on 2022-12-28 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmaker', '0002_load_mock_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='carmaker.project'),
        ),
    ]
