# Generated by Django 4.1 on 2022-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaker', '0003_alter_vehiclemodel_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
