# Generated by Django 4.1 on 2022-12-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmaker', '0004_alter_project_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carmaker.manufacturer'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carmaker.project'),
        ),
    ]
